In [37]:
! pip3 install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from openpyxl) (2.0.0)

In [61]:
import pandas
import json

# US Style Diet

In [39]:
us_style_diet = pandas.read_excel("assets/Diet Chart.xlsx", sheet_name="U.S.-Style Diet Chart")
us_style_diet

   Calorie       Carbs  Carbs.1     Protein Protein.1         Fat    Fat.1
0   Target  (calories)  (grams)  (calories)   (grams)  (calories)  (grams)
1        1         510      128         180        45         330       37
2      1.1         561      140         198        50         363       40
3      1.2         612      153         216        54         396       44
4      1.3         663      166         234        59         429       48
5      1.4         714      179         252        63         462       51
6      1.5         765      191         270        68         495       55
7      1.6         816      204         288        72         528       59
8      1.7         867      217         306        77         561       62
9      1.8         918      230         324        81         594       66
10     1.9         969      242         342        86         627       70
11       2        1020      255         360        90         660       73
12     2.1        1071      268         378        95         693       77
13     2.2        1122      281         396        99         726       81
14     2.3        1173      293         414       104         759       84
15     2.4        1224      306         432       108         792       88
16     2.5        1275      319         450       113         825       92

In [40]:
us_style_diet_jsons = []

for i in range(1, 17):
    data = {
        "name": "US Style Diet",
        "calorie": us_style_diet["Calorie"][i] * 1000.0,
        "carbs": us_style_diet["Carbs.1"][i],
        "protein": us_style_diet["Protein.1"][i],
        "fat": us_style_diet["Fat.1"][i]
    }
    us_style_diet_jsons.append(data)

# Vegetarian Style Diet

In [41]:
vegetarian_diet = pandas.read_excel("assets/Diet Chart.xlsx", sheet_name="Vegetarian Diet Chart")
vegetarian_diet

   Calorie       Carbs  Carbs.1     Protein Protein.1         Fat    Fat.1
0   Target  (calories)  (grams)  (calories)   (grams)  (calories)  (grams)
1        1         520      130         180        45         320       36
2      1.1         572      143         198        50         352       39
3      1.2         624      156         216        54         384       43
4      1.3         676      169         234        59         416       46
5      1.4         728      182         252        63         448       50
6      1.5         780      195         270        68         480       53
7      1.6         832      208         288        72         512       57
8      1.7         884      221         306        77         544       60
9      1.8         936      234         324        81         576       64
10     1.9         988      247         342        86         608       68
11       2        1040      260         360        90         640       71
12     2.1        1092      273         378        95         672       75
13     2.2        1144      286         396        99         704       78
14     2.3        1196      299         414       104         736       82
15     2.4        1248      312         432       108         768       85
16     2.5        1300      325         450       113         800       89

In [42]:
vegetarian_diet_jsons = []

for i in range(1, 17):
    data = {
        "name": "Vegetarian Style Diet",
        "calorie": vegetarian_diet["Calorie"][i] * 1000.0,
        "carbs": vegetarian_diet["Carbs.1"][i],
        "protein": vegetarian_diet["Protein.1"][i],
        "fat": vegetarian_diet["Fat.1"][i]
    }
    vegetarian_diet_jsons.append(data)

# Mediterranean Style Diet

In [43]:
mediterranean_style_diet = pandas.read_excel("assets/Diet Chart.xlsx", sheet_name="Mediterranean-Style Diet Chart")
mediterranean_style_diet

   Calorie       Carbs  Carbs.1     Protein Protein.1         Fat     Fat.1
0   Target  (calories)  (grams)  (calories)   (grams)  (calories)  ​(grams)
1        1         550      138         140        35         340        38
2      1.1         605      151         154        39         374        42
3      1.2         660      165         168        42         408        45
4      1.3         715      179         182        46         442        49
5      1.4         770      193         196        49         476        53
6      1.5         825      206         210        53         510        57
7      1.6         880      220         224        56         544        60
8      1.7         935      234         238        60         578        64
9      1.8         990      248         252        63         612        68
10     1.9        1045      261         266        67         646        72
11       2        1100      275         280        70         680        76
12     2.1        1155      289         294        74         714        79
13     2.2        1210      303         308        77         748        83
14     2.3        1265      316         322        81         782        87
15     2.4        1320      330         336        84         816        91
16     2.5        1375      344         350        88         850        94

In [44]:
mediterranean_style_diet["Calorie"]

0     Target
1          1
2        1.1
3        1.2
4        1.3
5        1.4
6        1.5
7        1.6
8        1.7
9        1.8
10       1.9
11         2
12       2.1
13       2.2
14       2.3
15       2.4
16       2.5
Name: Calorie, dtype: object

In [45]:
mediterranean_style_diet_jsons = []

for i in range(1, 17):
    data = {
        "name": "Vegetarian Style Diet",
        "calorie": mediterranean_style_diet["Calorie"][i] * 1000.0,
        "carbs": mediterranean_style_diet["Carbs.1"][i],
        "protein": mediterranean_style_diet["Protein.1"][i],
        "fat": mediterranean_style_diet["Fat.1"][i]
    }
    mediterranean_style_diet_jsons.append(data)

# 40 30 30 Style Diet

In [46]:
style_40_30_30 = pandas.read_excel("assets/Diet Chart.xlsx", sheet_name="40-30-30 Diet High Protein Char")
style_40_30_30

   Calorie       Carbs  Carbs.1     Protein Protein.1         Fat    Fat.1
0   Target  (calories)  (grams)  (calories)   (grams)  (calories)  (grams)
1        1         400      100         300        75         300       33
2      1.1         440      110         330        83         330       37
3      1.2         480      120         360        90         360       40
4      1.3         520      130         390        98         390       43
5      1.4         560      140         420       105         420       47
6      1.5         600      150         450       113         450       50
7      1.6         640      160         480       120         480       53
8      1.7         680      170         510       128         510       57
9      1.8         720      180         540       135         540       60
10     1.9         760      190         570       143         570       63
11       2         800      200         600       150         600       67
12     2.1         840      210         630       158         630       70
13     2.2         880      220         660       165         660       73
14     2.3         920      230         690       173         690       77
15     2.4         960      240         720       180         720       80
16     2.5        1000      250         750       188         750       83

In [47]:
style_40_30_30_jsons = []

for i in range(1, 17):
    data = {
        "name": "40 30 30 Style Diet",
        "calorie": style_40_30_30["Calorie"][i] * 1000.0,
        "carbs": style_40_30_30["Carbs.1"][i],
        "protein": style_40_30_30["Protein.1"][i],
        "fat": style_40_30_30["Fat.1"][i]
    }
    style_40_30_30_jsons.append(data)

# Summarize and Export

In [48]:
us_style_diet_jsons
vegetarian_diet_jsons
mediterranean_style_diet_jsons
style_40_30_30_jsons

[{'name': '40 30 30 Style Diet',
  'calorie': 1000.0,
  'carbs': 100,
  'protein': 75,
  'fat': 33},
 {'name': '40 30 30 Style Diet',
  'calorie': 1100.0,
  'carbs': 110,
  'protein': 83,
  'fat': 37},
 {'name': '40 30 30 Style Diet',
  'calorie': 1200.0,
  'carbs': 120,
  'protein': 90,
  'fat': 40},
 {'name': '40 30 30 Style Diet',
  'calorie': 1300.0,
  'carbs': 130,
  'protein': 98,
  'fat': 43},
 {'name': '40 30 30 Style Diet',
  'calorie': 1400.0,
  'carbs': 140,
  'protein': 105,
  'fat': 47},
 {'name': '40 30 30 Style Diet',
  'calorie': 1500.0,
  'carbs': 150,
  'protein': 113,
  'fat': 50},
 {'name': '40 30 30 Style Diet',
  'calorie': 1600.0,
  'carbs': 160,
  'protein': 120,
  'fat': 53},
 {'name': '40 30 30 Style Diet',
  'calorie': 1700.0,
  'carbs': 170,
  'protein': 128,
  'fat': 57},
 {'name': '40 30 30 Style Diet',
  'calorie': 1800.0,
  'carbs': 180,
  'protein': 135,
  'fat': 60},
 {'name': '40 30 30 Style Diet',
  'calorie': 1900.0,
  'carbs': 190,
  'protein': 143,
  'fat': 63},
 {'name': '40 30 30 Style Diet',
  'calorie': 2000.0,
  'carbs': 200,
  'protein': 150,
  'fat': 67},
 {'name': '40 30 30 Style Diet',
  'calorie': 2100.0,
  'carbs': 210,
  'protein': 158,
  'fat': 70},
 {'name': '40 30 30 Style Diet',
  'calorie': 2200.0,
  'carbs': 220,
  'protein': 165,
  'fat': 73},
 {'name': '40 30 30 Style Diet',
  'calorie': 2300.0,
  'carbs': 230,
  'protein': 173,
  'fat': 77},
 {'name': '40 30 30 Style Diet',
  'calorie': 2400.0,
  'carbs': 240,
  'protein': 180,
  'fat': 80},
 {'name': '40 30 30 Style Diet',
  'calorie': 2500.0,
  'carbs': 250,
  'protein': 188,
  'fat': 83}]

In [ ]:
data = []
data.extend(us_style_diet_jsons)
data.extend(vegetarian_diet_jsons)
data.extend(mediterranean_style_diet_jsons)
data.extend(style_40_30_30_jsons)

In [52]:
with open("diet_chart.json", 'w+') as file:
    json.dump(data, file)